const hotels = [
  {
    id: 1,
    name: "Grand Hotel Oslo",
    stars: 4,
    neighborhood: "Karl Johans gate",
    distanceKm: 0.8,
    pricePerNight: 1490,
    amenities: ["Gratis Wi-Fi", "Frokost", "Gym"],
    image: null,
    guestScore: 8.7,
    href: "infoside.html",
  },
  {
    id: 2,
    name: "Thon Hotel Opera",
    stars: 5,
    neighborhood: "Bjørvika",
    distanceKm: 1.4,
    pricePerNight: 2380,
    amenities: ["Spa", "Badebasseng", "Restaurant"],
    image: null,
    guestScore: 9.1,
    href: "infoside.html",
  },
  {
    id: 3,
    name: "Budget Inn Grünerløkka",
    stars: 3,
    neighborhood: "Grünerløkka",
    distanceKm: 2.2,
    pricePerNight: 940,
    amenities: ["Gratis Wi-Fi", "Felles kjøkken", "Vaskeri"],
    image: null,
    guestScore: 7.4,
    href: "infoside.html",
  },
  {
    id: 4,
    name: "Radisson Blu Plaza",
    stars: 5,
    neighborhood: "Sentrum",
    distanceKm: 0.3,
    pricePerNight: 3100,
    amenities: ["Gratis Wi-Fi", "Spa", "Gym", "Restaurant", "Parkering"],
    image: null,
    guestScore: 9.3,
    href: "infoside.html",
  },
  {
    id: 5,
    name: "Citybox Oslo",
    stars: 2,
    neighborhood: "Youngstorget",
    distanceKm: 0.6,
    pricePerNight: 650,
    amenities: ["Gratis Wi-Fi", "Parkering"],
    image: null,
    guestScore: 7.8,
    href: "infoside.html",
  },
  {
    id: 6,
    name: "Clarion Hotel The Hub",
    stars: 4,
    neighborhood: "Oslo S",
    distanceKm: 0.5,
    pricePerNight: 1890,
    amenities: ["Gratis Wi-Fi", "Frokost", "Gym", "Parkering"],
    image: null,
    guestScore: 8.5,
    href: "infoside.html",
  },
];