const hotels = [
  {
    id: 1,
    name: "Grand Hotel Oslo",
    stars: 4,
    neighborhood: "Karl Johans gate",
    distanceKm: 0.8,
    pricePerNight: 1490,
    amenities: ["Gratis Wi-Fi", "Frokost", "Gym"],
    image: null,
    guestScore: 8.7,
    href: "infoside.html",
  },
  {
    id: 2,
    name: "Thon Hotel Opera",
    stars: 5,
    pricePerNight: 2380,
    amenities: ["Spa", "Badebasseng", "Restaurant"],
    image: null,
    href: "infoside.html",
  },
  {
    id: 3,
    name: "Budget Inn Grünerløkka",
    stars: 3,
    neighborhood: "Grünerløkka",
    amenities: ["Gratis Wi-Fi", "Felles kjøkken", "Vaskeri"],
    image: null,
    href: "infoside.html",
  },
];